### PR TITLE
Change iOS plugin so compiles for Xcode 11

### PR DESCRIPTION
**Pull request by marchinram**
Also remove parse dependency not needed and set presenting view controller

### CODE REVIEW

**Comment by ragavendranbala** [comment]
Does it works on android also? Or need to use the official release only?

**Comment by marchinram** [comment]
Yeah I use it for both, Android wasn't causing me any issues, only the generated Xcode project had errors

**Comment by ragavendranbala** [comment]
Can you tell me how to download your pull request to fix the iOS issue on my project?

**Comment by marchinram** [comment]
You just run the build script `sh build_all.sh` I tried and saw a problem with the script will look into this

**Comment by marchinram** [comment]
Should work ok my only issue was I didn't set the `UNITY_EXE` env variable to the location of Unity executable, e.g: /Applications/Unity/Hub/Editor/2019.2.10f1/Unity.app/Contents/MacOS/Unity, after it's complete produces 2 .unitypackage files, `google-signin-plugin-1.0.4.unitypackage` and `GoogleSignIn-sample.unitypackage`, lemme know if you have issues with this @ragavendranbala

**Comment by marchinram** [comment]
handled here: https://github.com/googlesamples/google-signin-unity/pull/126

**Pull request closed without merging**
